---
- name: Setup SSH keys
  hosts: localhost
  gather_facts: yes
  vars:
    personal_private: 'id_personal_gh'
    personal_public: 'id_personal_gh.pub'
    tb_private: 'id_tb_gh'
    tb_public: 'id_tb_gh.pub'

  tasks:
    - name: Ensure the SSH folder exists
      become: yes
      ansible.builtin.file:
        path: "/home/tuliopaim/.ssh/"
        mode: 0700
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Install personal github private ssh key
      become: yes
      copy:
        src: "{{ ansible_user_dir }}/.dotfiles/ssh/{{ item }}"
        dest: "{{ ansible_user_dir }}/.ssh/{{ item }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        decrypt: yes
        mode: 0600
      with_items:
        - "{{ personal_private }}"
        - "{{ personal_public }}"
        - "{{ tb_private }}"
        - "{{ tb_public }}"
    
    - name: Copy config
      become: yes
      copy:
        src: "{{ ansible_user_dir }}/.dotfiles/ssh/config"
        dest: "{{ ansible_user_dir }}/.ssh/config"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0600

    - name: Eval the ssh-agent
      shell: |
        eval $(ssh-agent -s)
        ssh-add {{ ansible_user_dir }}/.ssh/{{ personal_private }}

    - name: Check if ~/.dotfiles exists
      stat:
        path: ~/.dotfiles
      register: dotfiles

    - name: Clone dotfiles repo
      git:
        repo: 'https://github.com/tuliopaim/dotfiles-wsl'
        dest: '~/.dotfiles/'
      when: not dotfiles.stat.exists

    - name: Setup dotfiles
      include_tasks: ~/.dotfiles/dev_env_tasks.yml
      when: not dotfiles.stat.exists
